[package]
name = "p12"
version = "0.1.4"
authors = ["hjiayz <hjiayz@gmail.com>"]
edition = "2018"
keywords = ["pkcs12", "pkcs"]
description = "pure rust pkcs12 tool"
homepage = "https://github.com/hjiayz/p12"
repository = "https://github.com/hjiayz/p12"
readme = "README.MD"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
yasna = { version = "0.3.1" }
getrandom = "0.1.14"
block-modes = "0.3.3"
block-cipher-trait = "0.6.2"
hmac = "0.7.1"
sha-1 = "0.8.1"
rc2 = "0.3.0"
des = "0.3.0"

[dev-dependencies]
hex = "0.4.2"
hex-literal = "0.2.1"
